-- Create selections table
create table if not exists public.selections (
    id bigint generated by default as identity primary key,
    session_id uuid references public.sessions(id),
    candidate_name text not null,
    total_score integer not null,
    success_rate decimal(5,2) not null,
    criteria_scores jsonb not null,
    rank_position integer not null,
    total_candidates integer not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.selections enable row level security;

-- Create policy to allow all operations (since this is a public app)
create policy "Allow all operations for selections"
    on public.selections
    for all
    using (true)
    with check (true);
